# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.SmallIntegerField()),
                ('critical', models.CharField(max_length=1)),
                ('num_day', models.IntegerField()),
                ('day_week', models.SmallIntegerField()),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Binnacle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('accomplished', models.TextField()),
                ('key', models.TextField()),
                ('againstkey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('action', models.SmallIntegerField()),
                ('time', models.TimeField()),
                ('num_day', models.IntegerField()),
                ('day_week', models.SmallIntegerField()),
                ('day_month', models.SmallIntegerField()),
                ('num_month', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accel_x', models.FloatField()),
                ('accel_y', models.FloatField()),
                ('accel_z', models.FloatField()),
                ('compass', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Action')),
                ('binnacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Binnacle')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Checkpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('velocity', models.FloatField()),
                ('course', models.FloatField()),
                ('provider', models.TextField()),
                ('time_gps', models.DateTimeField()),
                ('gps', models.IntegerField()),
                ('sensor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.SensorData')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Transfer'),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User'),
        ),
    ]
