# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='action',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='binnacle',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='checkpoint',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='transfer',
        ),
        migrations.AddField(
            model_name='action',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binnacle',
            name='action',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.Action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='binnacle',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sensor_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.SensorData'),
        ),
    ]
