# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20160511_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='id',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sensor_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='data.SensorData'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
